### ISSUE TITLE
OSError: Failed to interpret file './data/data.npk' as a pickle

### ISSUE THREAD

**Issue by daozhangcisco** [zc8340311/RobustAutoencoder#8]
When I run the basic AE code, I got the error loading the file
~/Desktop/RobustAutoencoder/model/BasicAutoencoder$ python3 DeepAE.py 
Traceback (most recent call last):
  File "/home/daozhang/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    return pickle.load(fid, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 598: ordinal not in range(128)

Traceback (most recent call last):
  File "/home/daozhang/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    return pickle.load(fid, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 598: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "DeepAE.py", line 94, in <module>
    x = np.load(r"./data/data.npk")
  File "/home/daozhang/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 431, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file './data/data.npk' as a pickle

**Comment by daozhangcisco** [comment]
got it from the notebook notes. It would be nice to put the notes in the py files as well
